### ISSUE TITLE
error with python.exe get-pip.py

### ISSUE THREAD

**Issue by stxdigitizing** [manu12121999/RemoveBG-GIMP#11]
ERROR: Exception when installing RemoveBG-GIMP will not show up in GIMP 2.10.30

````
ERROR: Exception:
Traceback (most recent call last):
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_internal/commands/install.py", line 404, in run
    pycompile=options.compile,
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_internal/req/req_install.py", line 824, in install
    requested=self.user_supplied,
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_internal/operations/install/wheel.py", line 845, in install_wheel
    requested=requested,
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_internal/operations/install/wheel.py", line 747, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_vendor/distlib/scripts.py", line 418, in make_multiple
    filenames.extend(self.make(specification, options))
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_internal/operations/install/wheel.py", line 483, in make
    return super(PipScriptMaker, self).make(specification, options)
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_vendor/distlib/scripts.py", line 407, in make
    self._make_script(entry, filenames, options=options)
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_vendor/distlib/scripts.py", line 307, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_vendor/distlib/scripts.py", line 242, in _write_script
    launcher = self._get_launcher('t')
  File "c:/users/jlope/appdata/local/temp/tmpr_vc8b/pip.zip/pip/_vendor/distlib/scripts.py", line 386, in _get_launcher
    raise ValueError(msg)
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib`
```

**Comment by Ocelotsden** [comment]
Did you ever find a fix for this? I have the same issue and have been searching without luck on any of the fixes I found

**Comment by manu12121999** [comment]
Newer versions of the plugin dont require this step of the installation anymore.
