### ISSUE TITLE
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib

### ISSUE THREAD

**Issue by Tissot1** [manu12121999/RemoveBG-GIMP#13]
Hi. 
I tried removebg-gimp, but the filter does not show up in the menu after restarting gimp. 
I tried removebg-gimp-requests, but that is throwing ValueError: Unable to find resource t64.exe in package pip._vendor.distlib

`
C:\Windows\System32>cd "C:\Program Files\GIMP 2\bin\"

C:\Program Files\GIMP 2\bin>curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1863k  100 1863k    0     0  7335k      0 --:--:-- --:--:-- --:--:-- 7365k

C:\Program Files\GIMP 2\bin>python.exe get-pip.py
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting pip<21.0
  Downloading pip-20.3.4-py2.py3-none-any.whl (1.5 MB)
     |################################| 1.5 MB 4.2 MB/s
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: pip, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
  Rolling back uninstall of pip
  Moving to c:\program files\gimp 2\lib\python2.7\site-packages\pip
   from c:\program files\gimp 2\lib\python2.7\site-packages\~ip
  Moving to c:\program files\gimp 2\lib\python2.7\site-packages\pip-20.0.2-py2.7.egg-info
   from c:\program files\gimp 2\lib\python2.7\site-packages\~ip-20.0.2-py2.7.egg-info
ERROR: Exception:
Traceback (most recent call last):
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_internal/commands/install.py", line 404, in run
    pycompile=options.compile,
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_internal/req/req_install.py", line 824, in install
    requested=self.user_supplied,
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_internal/operations/install/wheel.py", line 845, in install_wheel
    requested=requested,
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_internal/operations/install/wheel.py", line 747, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_vendor/distlib/scripts.py", line 418, in make_multiple
    filenames.extend(self.make(specification, options))
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_internal/operations/install/wheel.py", line 483, in make
    return super(PipScriptMaker, self).make(specification, options)
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_vendor/distlib/scripts.py", line 407, in make
    self._make_script(entry, filenames, options=options)
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_vendor/distlib/scripts.py", line 307, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_vendor/distlib/scripts.py", line 242, in _write_script
    launcher = self._get_launcher('t')
  File "c:/users/user1/appdata/local/temp/tmppcsoks/pip.zip/pip/_vendor/distlib/scripts.py", line 386, in _get_launcher
    raise ValueError(msg)
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib

C:\Program Files\GIMP 2\bin>python.exe -m pip install requests
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: requests in c:\program files\gimp 2\lib\python2.7\site-packages (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\program files\gimp 2\lib\python2.7\site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\program files\gimp 2\lib\python2.7\site-packages (from requests) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\program files\gimp 2\lib\python2.7\site-packages (from requests) (1.25.6)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\gimp 2\lib\python2.7\site-packages (from requests) (2019.9.11)

C:\Program Files\GIMP 2\bin>

`

**Comment by manu12121999** [comment]
closed issue for using old installation method
