### ISSUE TITLE
Could be corrupted in mandarin environment.

### ISSUE THREAD

**Issue by Meavel** [manu12121999/RemoveBG-GIMP#15]
I faced a problem when I install into a mandarin windows 10 environment. That means, when I install windows 10 in Mandarin as primary language and define a mandarin username, I cannot use removebg-gimp. This is  the error message.

Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 741, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 362, in run_script
    return apply(function, params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\remove_background.py", line 44, in remove_background
    pdb.file_png_save_defaults(image, layer_copy, f, f)
RuntimeError: 無法開啟‘c:\users\�^�߫�\appdata\local\temp\temp.png’來寫入資料：Invalid argument

remark 無法開啟=cannot open
remark 來寫入資料=to write data (into the following location)

程序「file-png-save-defaults」的呼叫錯誤：

無法開啟‘c:\users\�^�߫�\appdata\local\temp\temp.png’來寫入資料：Invalid argument

remark 程序=programme
remark 的呼叫錯誤= something's calling failure

**Comment by Meavel** [comment]
Since nobody help me, so I install another version of gimp portable to reinstall the removebg plug-in.
