### ISSUE TITLE
[Windows] Unable to Run

### ISSUE THREAD

**Issue by kingtysonsworld** [manu12121999/RemoveBG-GIMP#2]
I'm receiving this error when trying to run the plug-in: _RuntimeError: Could not open 'C:\tmp\temp.png' for writing: No such file or directory_

Traceback More Information
_Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 740, in response
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 361, in run_script
    return apply(function, params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\remove_background.py", line 38, in remove_background
    pdb.file_png_save_defaults(image, layer_copy, f, f)
RuntimeError: Could not open 'C:\tmp\temp.png' for writing: No such file or directory_

![Screenshot (115)_LI](https://user-images.githubusercontent.com/66930724/84931576-f763f300-b0a0-11ea-8b89-9bb3aac47c76.jpg)

**Comment by manu12121999** [comment]
A temporaly solution would be to make a directory in C:  called tmp.
I thought it was standart to have such this directory.
That you for that issue, I am going to change that as soon as possible

**Comment by manu12121999** [comment]
I found a solution, but I am not sure if it works for everyone. Please tell me if it worked for you. Code is in the master branch.
